# frozen_string_literal: true
require 'rake/testtask'
require_relative 'lib/runner'

namespace :solve do

  (1..25).each do |i|
    desc "Run day #{i}"
    task i.to_s.to_sym do
      Aoc2024::Runner.new.call(i)
    end
    if i < 10
      task ('0' + i.to_s).to_sym => i.to_s.to_sym
    end
  end
end

Rake::TestTask.new do |t|
  t.pattern = 'test/*_test.rb'
end